version: '3.1'
services:
  mongo:
    image: mongo
    container_name: pp-database
    ports: 
      - "27017:27017"
    volumes: 
      - "C:/Projects/party-partner/data:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret