version: 2
jobs:
  build:
    working_directory: ~/party-partner
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
        name: Show current branch
        command: echo ${CIRCLE_BRANCH}
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: 
        name: Install local dependencies
        command: npm install
      - save_cache:
        key: v1-dependencies-{{ checksum "package.json" }}
        paths:
          - node_modules
      - run: 
        name: Unit and integrations teststing
        command: npm test
      - run: 
        name: Starting e2e testing
        command: npm test:e2e
      - run:
        name: Building
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run build:prod
          else
              npm run build:dev
          fi
      - save_cache:
        key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - dist
  deploy:
    working_directory: ~/party-partner
    docker:
      - image: circleci/node:10.15.0
    steps:
      - run: echo "TODO"
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            # The deploy job will only run on the filtered branches and
            # require the build job to be successful before it starts
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only:
                            - develop
                            - master